chore(requirements.txt): add pydantic==1.10.9 as a new dependency
Temporary fix pydantic breakage

Traceback (most recent call last):
  File "/home/runner/work/genshin-stats/genshin-stats/main.py", line 7, in <module>
    import genshin
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/genshin/__init__.py", line 9, in <module>
    from . import models, utility
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/genshin/models/__init__.py", line 2, in <module>
    from .genshin import *
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/genshin/models/genshin/__init__.py", line 2, in <module>
    from .calculator import *
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/genshin/models/genshin/calculator.py", line 9, in <module>
    from genshin.models.model import Aliased, APIModel, Unique
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/genshin/models/model.py", line 37, in <module>
    class APIModel(pydantic.BaseModel, abc.ABC):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/genshin/models/model.py", line 126, in APIModel
    @pydantic.root_validator()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

Signed-off-by: Ahmad Thoriq Najahi <najahi@zephyrus.id>